export const SET_MENU_OPTION = 'SET_MENU_OPTION'
export const ASSIGN_MENU_OPTION = 'ASSIGN_MENU_OPTION'

export const ADD_ITEM = 'ADD_ITEM'
export const SET_RECORD = 'SET_RECORD'

export const SET_RESULTS = 'SET_RESULTS'

export const LOGIN = 'LOGIN'
export const SET_USER = 'SET_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHANGE_PASSWORD_ALERT = 'CHANGE_PASSWORD_ALERT'

export const LOAD_BRANCHES = 'LOAD_BRANCHES'
export const SET_BRANCHES = 'SET_BRANCHES'
export const SAVE_BRANCH = 'SAVE_BRANCH'
export const DELETE_BRANCH = 'DELETE_BRANCH'

export const LOAD_SECTORS = 'LOAD_SECTORS'
export const SET_SECTORS = 'SET_SECTORS'
export const SAVE_SECTOR = 'SAVE_SECTOR'
export const DELETE_SECTOR = 'DELETE_SECTOR'

export const LOAD_POSITIONS = 'LOAD_POSITIONS'
export const SET_POSITIONS = 'SET_POSITIONS'
export const SAVE_POSITION = 'SAVE_POSITION'
export const DELETE_POSITION = 'DELETE_POSITION'
export const LOAD_SECTOR_POSITIONS = 'LOAD_SECTOR_POSITIONS'

export const LOAD_POSITION_SECTOR = 'LOAD_POSITION_SECTOR'
export const SET_POSITION_SECTOR = 'SET_POSITION_SECTOR'

export const LOAD_PROFILES = 'LOAD_PROFILES'
export const SET_PROFILES = 'SET_PROFILES'

export const LOAD_STATUS = 'LOAD_STATUS'
export const SET_STATUS = 'SET_STATUS'

export const LOAD_EMPLOYEES = 'LOAD_EMPLOYEES'
export const LOAD_EMPLOYEE = 'LOAD_EMPLOYEE'
export const SET_EMPLOYEES = 'SET_EMPLOYEES'
export const SET_EMPLOYEE = 'SET_EMPLOYEE'
export const SAVE_EMPLOYEE = 'SAVE_EMPLOYEE'
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'
export const LOAD_BRANCH_EMPLOYEES = 'LOAD_BRANCH_EMPLOYEES'

export const LOAD_USERS = 'LOAD_USERS'
export const SET_USERS = 'SET_USERS'
export const SAVE_USER = 'SAVE_USER'
export const DELETE_USER = 'DELETE_USER'

export const LOAD_TIMEOFFS = 'LOAD_TIMEOFFS'
export const SET_TIMEOFFS = 'SET_TIMEOFFS'
export const SAVE_TIMEOFF = 'SAVE_TIMEOFF'
export const DELETE_TIMEOFF = 'DELETE_TIMEOFF'

export const LOAD_BUDGETS = 'LOAD_BUDGETS'
export const SET_BUDGETS = 'SET_BUDGETS'
export const SAVE_BUDGET = 'SAVE_BUDGET'
export const DELETE_BUDGET = 'DELETE_BUDGET'

export const LOAD_SCHEDULES = 'LOAD_SCHEDULES'
export const SET_SCHEDULES = 'SET_SCHEDULES'
export const SAVE_SCHEDULE = 'SAVE_SCHEDULE'
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE'
export const SCHEDULE_VERIFY_INPUT = 'SCHEDULE_VERIFY_INPUT'
export const LOAD_TIMEOFF = 'LOAD_TIMEOFF'
export const SET_TIMEOFF = 'SET_TIMEOFF'

export const LOAD_BUDGET_TIMEOFF = 'LOAD_BUDGET_TIMEOFF'
export const SET_BUDGET_TIMEOFF = 'SET_BUDGET_TIMEOFF'

export const SET_VALUE = 'SET_VALUE'
export const SET_AUTOCOMPLETE_VALUE = 'SET_AUTOCOMPLETE_VALUE'
